[brand_patterns]

[brand_patterns.financial]

[brand_patterns.financial.paypal]
domains = ["paypal.com", "paypal-communications.com"]

[brand_patterns.financial.chase]
domains = ["chase.com", "jpmorgan.com", "jpmorganchase.com"]

[brand_patterns.financial.wells_fargo]
domains = ["wellsfargo.com", "wf.com"]

[brand_patterns.financial.bank_of_america]
domains = ["bankofamerica.com", "bofa.com"]

[brand_patterns.financial.citi]
domains = ["citi.com", "citicards.com", "info6.citi.com"]

[brand_patterns.financial.american_express]
domains = ["americanexpress.com", "amex.com"]

[brand_patterns.financial.discover]
domains = ["discover.com", "discovercard.com"]

[brand_patterns.technology]

[brand_patterns.technology.microsoft]
domains = ["microsoft.com", "outlook.com", "hotmail.com", "live.com", "msn.com"]

[brand_patterns.technology.google]
domains = ["google.com", "gmail.com", "googlemail.com", "youtube.com"]

[brand_patterns.technology.apple]
domains = ["apple.com", "icloud.com", "me.com", "mac.com"]

[brand_patterns.technology.amazon]
domains = ["amazon.com", "amazonses.com", "aws.com"]

[brand_patterns.technology.facebook]
domains = ["facebook.com", "meta.com", "instagram.com", "whatsapp.com"]

[brand_patterns.business_services]

[brand_patterns.business_services.docusign]
domains = ["docusign.com", "docusign.net"]

[brand_patterns.business_services.adobe]
domains = ["adobe.com", "adobesign.com"]

[brand_patterns.business_services.salesforce]
domains = ["salesforce.com", "force.com"]

[brand_patterns.business_services.dropbox]
domains = ["dropbox.com", "dropboxmail.com"]

[brand_patterns.ecommerce]

[brand_patterns.ecommerce.shopify]
domains = ["shopify.com", "myshopify.com"]

[brand_patterns.ecommerce.ebay]
domains = ["ebay.com", "ebayinc.com"]

[brand_patterns.ecommerce.walmart]
domains = ["walmart.com", "wal-mart.com"]

[brand_patterns.ecommerce.target]
domains = ["target.com", "targetcorp.com"]

[brand_patterns.shipping]

[brand_patterns.shipping.ups]
domains = ["ups.com", "upsmyChoice.com"]

[brand_patterns.shipping.fedex]
domains = ["fedex.com", "fedexoffice.com"]

[brand_patterns.shipping.usps]
domains = ["usps.com", "usps.gov"]

[brand_patterns.shipping.dhl]
domains = ["dhl.com", "dhl.de"]

[brand_patterns.healthcare]

[brand_patterns.healthcare.cvs]
domains = ["cvs.com", "cvshealth.com"]

[brand_patterns.healthcare.walgreens]
domains = ["walgreens.com", "walgreensbootsalliance.com"]

[brand_patterns.healthcare.kaiser]
domains = ["kp.org", "kaiserpermanente.org"]

[exclusion_patterns]

[exclusion_patterns.job_related_senders]
domains = [
    "linkedin.com",
    "indeed.com",
    "glassdoor.com",
    "backstage.com",
    "ziprecruiter.com",
    "monster.com",
    "careerbuilder.com"
]

[exclusion_patterns.newsletter_senders]
domains = [
    "substack.com",
    "medium.com",
    "mailchimp.com",
    "constantcontact.com",
    "campaignmonitor.com"
]

[exclusion_patterns.legitimate_bulk_senders]
domains = [
    "sendgrid.net",
    "mailgun.com",
    "amazonses.com",
    "sparkpostmail.com",
    "klaviyomail.com"
]
