# Legitimate Bulk Email Services
# These are trusted email infrastructure providers

[services]
domains = [
    "mailchimp.com",
    "constantcontact.com",
    "sendgrid.net",
    "mailgun.org",
    "amazonses.com",
    "sparkpostmail.com",
    "campaignmonitor.com",
    "aweber.com",
    "getresponse.com",
    "convertkit.com",
    "klaviyo.com",
    "hubspot.com"
]
