[feature_scoring]

[feature_scoring.link_analysis]
enabled = true

[feature_scoring.sender_alignment]
enabled = true

[feature_scoring.context_analysis]
enabled = true

[feature_scoring.invoice_analysis]
enabled = true

[feature_scoring.domain_analysis]
enabled = true

[feature_scoring.domain_reputation]
enabled = true

[feature_scoring.brand_impersonation]
enabled = true

[feature_scoring.financial_validation]
enabled = true
