[legitimate_domains]
financial_institutions = [
    "chase.com",
    "wellsfargo.com",
    "bankofamerica.com",
    "citi.com",
    "citicards.com",
    "info6.citi.com",
    "info.citi.com",
    "mail.citi.com",
    "usbank.com",
    "capitalone.com",
    "discover.com",
    "services.discover.com",
    "americanexpress.com",
    "schwab.com",
    "fidelity.com",
    "vanguard.com",
    "tdameritrade.com",
    "etrade.com",
    "robinhood.com",
    "paypal.com",
    "stripe.com",
    "square.com",
    "venmo.com",
    "zelle.com"
]

email_service_providers = [
    "sendgrid.net",
    "mailgun.com",
    "mailchimp.com",
    "constantcontact.com",
    "klaviyomail.com",
    "sparkpostmail.com",
    "amazonses.com",
    "outlook.com",
    "gmail.com",
    "yahoo.com",
    "aol.com"
]

major_brands = [
    "amazon.com",
    "microsoft.com",
    "google.com",
    "apple.com",
    "facebook.com",
    "meta.com",
    "campaigns.meta.com",
    "netflix.com",
    "spotify.com",
    "adobe.com",
    "salesforce.com",
    "shopify.com",
    "ebay.com",
    "walmart.com",
    "target.com",
    "bestbuy.com",
    "homedepot.com",
    "lowes.com"
]

business_services = [
    "docusign.com",
    "hellosign.com",
    "dropbox.com",
    "box.com",
    "slack.com",
    "zoom.us",
    "teams.microsoft.com",
    "webex.com",
    "gotomeeting.com"
]

job_platforms = [
    "linkedin.com",
    "indeed.com",
    "glassdoor.com",
    "monster.com",
    "careerbuilder.com",
    "ziprecruiter.com",
    "backstage.com",
    "send.backstage.com"
]

educational_services = [
    "kiwico.com",
    "coursera.org",
    "udemy.com",
    "edx.org",
    "khan.academy.org"
]

civic_organizations = [
    "imcivicaction.org",
    "actionnetwork.org",
    "change.org",
    "moveon.org",
    "public.govdelivery.com",
    "govdelivery.com"
]

business_tools = [
    "quickbooks.com",
    "freshbooks.com",
    "invoicecloud.com",
    "billpay.com",
    "autopay.com",
    "paymi.com",
    "epay.com",
    "netsuite.com",
    "concur.com",
    "expensify.com"
]

creative_services = [
    "namemaker.com",
    "canva.com",
    "figma.com",
    "behance.net"
]

news_media = [
    "nytimes.com",
    "washingtonpost.com",
    "wsj.com",
    "reuters.com",
    "ap.org",
    "bbc.com",
    "cnn.com",
    "foxnews.com"
]

subscription_services = [
    "medium.com",
    "substack.com",
    "patreon.com",
    "onlyfans.com"
]

pest_control = [
    "exterminators.com",
    "pestconnect.com",
    "orkin.com",
    "terminix.com"
]

technology = [
    "asus.com",
    "dell.com",
    "hp.com",
    "lenovo.com",
    "intel.com",
    "amd.com",
    "nvidia.com"
]

travel = [
    "bcdtravel.com",
    "expedia.com",
    "booking.com",
    "airbnb.com",
    "uber.com",
    "lyft.com"
]

food_delivery = [
    "doordash.com",
    "ubereats.com",
    "grubhub.com",
    "postmates.com"
]

social_media = [
    "twitter.com",
    "instagram.com",
    "youtube.com",
    "tiktok.com",
    "snapchat.com",
    "pinterest.com",
    "reddit.com"
]
